### ISSUE TITLE
pull req #91 broke something.

### ISSUE THREAD

**Issue by linas** [opencog/ros-behavior-scripting#110]
After merging pull req #91, I get the following being printed, as fast as possible, when I run

```
guile -l btree-psi.scm
```

This:

```
(Eva expresses amused emotion for 3.0 seconds, with intensity 0.5 )
(Eva expresses amused emotion for 3.0 seconds, with intensity 0.5 )
(Eva expresses amused emotion for 3.0 seconds, with intensity 0.5 )
(Eva expresses amused emotion for 3.0 seconds, with intensity 0.5 )
(Eva expresses amused emotion for 3.0 seconds, with intensity 0.5 )
```

which clearly comes from this:
https://github.com/yenat/ros-behavior-scripting/blob/117954b7e4301223d6bf8c9997e99c0025d1364f/src/orchestrate.scm#L235-L249

I will try to disable this

**Comment by linas** [comment]
pull req #111 stubs out the code until its fixed

**Comment by amebel** [comment]
Saw into this, the rules should be ported to psi-dynamics rules, that will affect the level of positive/negative valence or some other cpm parameter. @eddiemonroe comments?

**Comment by linas** [comment]
I think pull req #120 might fix this. It certainly removes the stubbed-out code.

**Comment by linas** [comment]
closing I assume this is fixed.
