### ISSUE TITLE
Unbound variable "chat-state"

### ISSUE THREAD

**Issue by wenwei-dev** [opencog/ros-behavior-scripting#69]
Run this to reproduce the error
`rostopic pub -1 /robot/speech_events std_msgs/String "start"`

```
ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: chat-state
ABORT: unbound-variable
```

**Comment by linas** [comment]
The module `eva-model` defines this.   Some subsystem failed to  `(use-modules (opencog eva-model))`  Not sure which.

**Comment by linas** [comment]
Anyway .. is this still an issue? There have been a log of changes to the chatbot in the last 3 days; this might be fixed already?

**Comment by wenwei-dev** [comment]
I just test it, and the bug is still there.

**Comment by leungmanhin** [comment]
Strange, I didn't get this error, was the ros-behavior-scripting running?

**Comment by wenwei-dev** [comment]
Yes, it was running. It happened when I chatted with it. But this is not
urgent and important.

**Comment by linas** [comment]
Closing, I assume this is no longer an issue
