### ISSUE TITLE
Close eyes during sleep

### ISSUE THREAD

**Issue by linas** [opencog/ros-behavior-scripting#7]
There is a sleep sequence, where, if the room is empty, and she is bored for long enough, she falls asleep.  However, there does not seem to be any close-the-eyelids animation to go with this.  This needs fixing.

**Comment by vytasrgl** [comment]
#9  Adds the functions to go sleep/wake up.

**Comment by vytasrgl** [comment]
Blender API needs to be updated with latest version to make transition smooth

**Comment by linas** [comment]
Thanks, I think knew that and just forgot...
