### ISSUE TITLE
tracking stops in case of single detected face after face being lost and re-detected

### ISSUE THREAD

**Issue by yantrabuddhi** [opencog/ros-behavior-scripting#83]
When we run the behavior tree from hanson HEAD repository, initially the robot detects the face and tracks it. However on loosing the track of face and re-detecting any single face the tracking does not happen. When there are more faces detected however the tracking starts working while blender head moves in strange way. 
An observation is that this happens when face is re-detected and exactly after the glance at new face happens a someone left rule is triggered and then the tracking does not happen

**Comment by linas** [comment]
@AmeBel or @rtrautlein shoul dbe able to help with that. The psi rules should be identical to the old behavior tree riles, they were not changed.  So an obvious thing to ch3eck to to make sure that the visible faces state is changing correctly when faces appear and disappear.

Commonting out the delete-atom clauses will definitely mess up face tracking.

**Comment by linas** [comment]
Is this still an issue?

**Comment by amebel** [comment]
issue is resolved.
